# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os:
            - image: "ubuntu-latest"
              short: "linux"
            - image: "macos-latest"
              short: "osx"
        qiime:
            - version: "2020.4"
              tag: "release"
            - version: "2020.6"
              tag: "release" 
            - version: "latest"
              tag: "staging"
    runs-on: "${{matrix.os.image}}"

    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: goanpeca/setup-miniconda@v1
      with:
       python-version: 3.6
    - shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Install Qiime 2
      shell: bash -l {0}
      run: |
        wget https://raw.githubusercontent.com/qiime2/environment-files/master/${{matrix.qiime.version}}/${{matrix.qiime.tag}}/qiime2-${{matrix.qiime.version}}-py36-${{matrix.os.short}}-conda.yml
        conda env create -q -n qiime2-dev --file qiime2-${{matrix.qiime.version}}-py36-${{matrix.os.short}}-conda.yml
        rm qiime2-${{matrix.qiime.version}}-py36-${{matrix.os.short}}-conda.yml
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda activate qiime2-dev
        conda install -yq -c conda-forge -c \
            bioconda cobra umap-learn jinja2 loky pyarrow loguru tqdm
        conda install -yq -c ibmdecisionoptimization cplex
        pip install -e .
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=80 --statistics
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        conda activate qiime2-dev
        pip install pytest pytest-benchmark pytest-cov
        pytest --benchmark-skip --cov=q2_micom --cov-report=xml
    - name: Upload to codecov
      if: matrix.os.image == 'ubuntu-latest'
      uses: codecov/codecov-action@v1
